[config]
author = "Rimi Kanokawa"
title = "Luminous: the Dream"
resource_root = "LuminousTheDreamFiles"
modified_mode = "none"

[entry]
name = "Luminous the Dream (Web)"
path = "luminous/title.html"

[pdf]
top-level-division = "chapter"
fonts = [
    "Fira Sans,Main,BoldWeight=500",
    "Dancing Script,Title",
    "Cormorant Infant",
    "Gothic A1,Fallback",
]
no_c_span_space = true

[pdf.books]
book_main = "Starlit Skies"

[alt]
